# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: OSM-PNR96 Addresstäckning
email: "&#115;amuel <!--\" -->snabel-a kodafritt punkt se"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/pnr96addrstats/jekyll" # the subpath of your site, e.g. /blog
url: "http://samuellb.users.openstreetmap.se" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
